## Load df's

In [1]:
from pathlib import Path
import pandas as pd
from data_cleaning.utils import log_standard_scale, peek

CLEANED_DIR = Path("cleaned_data")

In [4]:
hai_df = pd.read_csv(CLEANED_DIR / "hai_cleaned.csv", low_memory=False)
print(hai_df.shape)
peek(hai_df)

(128177, 5)

    participant_id  timepoint                  virus_strain  value material
0  2016_UGA.ID_001        0.0  H1N1 A/South Carolina/1/1918   20.0  Unknown
1  2016_UGA.ID_001       28.0  H1N1 A/South Carolina/1/1918   40.0  Unknown
2  2016_UGA.ID_002        0.0  H1N1 A/South Carolina/1/1918    5.0  Unknown
3  2016_UGA.ID_002       28.0  H1N1 A/South Carolina/1/1918    5.0  Unknown
4  2016_UGA.ID_003        0.0  H1N1 A/South Carolina/1/1918   80.0  Unknown

In [2]:
participants_df = pd.read_csv(CLEANED_DIR / "participants_cleaned.csv", low_memory=False)
print(participants_df.shape)
peek(participants_df)

(3960, 6)

     participant_id biological_sex   race geolocation arm_name   age
0  SDY269.SUB112836         Female  White     Georgia    Other  28.0
1  SDY269.SUB112849         Female  Black     Georgia    Other  39.0
2  SDY269.SUB112854           Male  Black     Georgia    Other  46.0
3  SDY269.SUB112860         Female  White     Georgia    Other  32.0
4  SDY269.SUB112881         Female  Black     Georgia    Other  29.0

In [3]:
flow_df = pd.read_csv(CLEANED_DIR / "flow_cleaned.csv", low_memory=False)
print(flow_df.shape)
peek(flow_df)

(213624, 8)

,participant_id,timepoint,parent_population,population_definition,name,unit,value,material
0,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+,Freq. of,WBC",live CD45+ cells,cells/uL,176.220000,blood
1,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ1: CD27,, IgD+,Freq. of,C...",Naive B cells,cells/uL,112.780800,blood
2,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ2: CD27+,, IgD+,Freq. of,...",Memory class switched + non-class switched B c...,cells/uL,12.370644,blood
3,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ3: CD27+,, IgD,Freq. of,C...",Memory class switched B cells,cells/uL,21.322620,blood
4,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ4: CD27,, IgD,Freq. of,CD19+",B cells,cells/uL,29.781180,blood

In [ ]:
t2019 = pd.read_parquet(CLEANED_DIR / "transcriptomics_2019_UGA_cleaned.parquet")
t2020 = pd.read_parquet(CLEANED_DIR / "transcriptomics_2020_UGA_cleaned.parquet")
tsdy2867 = pd.read_parquet(CLEANED_DIR / "transcriptomics_SDY2867_cleaned.parquet")
transcriptomics = pd.concat([t2019, t2020, tsdy2867], axis=0, ignore_index=True)
print(transcriptomics.shape)

## Merge one by one

In [ ]:
merged = participants_df.merge(flow_df, on="participant_id", how="left")
print(merged.shape)

In [ ]:
merged = merged.merge(hai_df, on="participant_id", how="left", suffixes=("", "_hai"))
print(merged.shape)

In [ ]:
merged = merged.merge(transcriptomics, on="participant_id", how="left")
print(merged.shape)
peek(merged)