In [1]:
# Import required libraries
import os
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv('../data/train_flow.tsv', sep='\t', low_memory=False)
df = df.drop(columns=['flow_id'])
df.head()

,participant_id,timepoint,parent_population,population_defnition,name,unit,value,material
0,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+,Freq. of,WBC",live CD45+ cells?,cells/uL,176.220000,blood
1,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ1: CD27,, IgD+,Freq. of,C...",Naive B cells,cells/uL,112.780800,blood
2,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ2: CD27+,, IgD+,Freq. of,...",Memory class switched + non-class switched B c...,cells/uL,12.370644,blood
3,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ3: CD27+,, IgD,Freq. of,C...",Memory class switched B cells,cells/uL,21.322620,blood
4,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ4: CD27,, IgD,Freq. of,CD19+",B cells,cells/uL,29.781180,blood

In [3]:
# Rename typo column
df = df.rename(columns={'population_defnition': 'population_definition'})

# Clean material column (standardize labels)
df['material'] = df['material'].replace({
    'specimen type: other': 'Other'
})

# Clean name column (remove trailing '?', standardize case)
df['name'] = df['name'].str.rstrip('?').str.strip()
df['name'] = df['name'].str.capitalize()

# todo not sure if the same thing Standardize unit column
# df['unit'] = df['unit'].replace({'percentile': 'percentage'})

df.head()

,participant_id,timepoint,parent_population,population_definition,name,unit,value,material
0,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+,Freq. of,WBC",Live cd45+ cells,cells/uL,176.220000,blood
1,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ1: CD27,, IgD+,Freq. of,C...",Naive b cells,cells/uL,112.780800,blood
2,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ2: CD27+,, IgD+,Freq. of,...",Memory class switched + non-class switched b c...,cells/uL,12.370644,blood
3,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ3: CD27+,, IgD,Freq. of,C...",Memory class switched b cells,cells/uL,21.322620,blood
4,SDY180.SUB119292,-7.0,NaN,"WBC/CD19+SCC/CD19+/nQ4: CD27,, IgD,Freq. of,CD19+",B cells,cells/uL,29.781180,blood

In [4]:
# Print all columns and their unique values
for col in df.columns:
    print(f"{col}: {df[col].unique()}\n")

participant_id: <StringArray>
['SDY180.SUB119292', 'SDY180.SUB119293', 'SDY180.SUB119294',
 'SDY180.SUB119295', 'SDY180.SUB119296', 'SDY180.SUB119297',
 'SDY180.SUB119262', 'SDY180.SUB119264', 'SDY180.SUB119266',
 'SDY180.SUB119267',
 ...
  'SDY80.SUB114500',  'SDY80.SUB114502',  'SDY80.SUB114503',
  'SDY80.SUB114504',  'SDY80.SUB114506',  'SDY80.SUB114507',
  'SDY80.SUB114508',  'SDY80.SUB114510',  'SDY80.SUB114511',
  'SDY80.SUB114512']
Length: 264, dtype: str

timepoint: [ -7.    0.    1.   10.   14.   21.   28.    3.    7.    0.5   2.    4.
   5.    6.    8.    9.  120.  240.   -5.   90.   70. ]

parent_population: <StringArray>
[                                          nan,
                                        'PBMC',
                                'CD3+ T cells',
                                'CD4+ T cells',
                 'Central Memory CD4+ T cells',
                       'Effector CD4+ T cells',
                'Effector Memory CD4+ T cells',
                          'Naive CD4+ T cells',
                                'CD8+ T cells',
                'Effector Memory CD8+ T cells',
 ...
            '(as of viable CD45+CD3+CD8+CD4-)',
     '(as of viable CD45+CD3+CD8+CD4-CD45RA+)',
     '(as of viable CD45+CD3+CD8+CD4-CD45RA-)',
                    '(as of viable CD45+CD3+)',
           '(as of viable CD45+CD3+ CD4+CD8-)',
            '(as of viable CD45+CD3+CD4+CD8-)',
   '(as of viable CD45+CD3+ CD4+CD8- CD45RA-)',
    '(as of viable CD45+CD3+ CD4+CD8- CD161+)',
 '(as of viable CD45+CD3+ CD4+CD8-) histogram',
    '(as of viable CD45+CD3+ CD4+CD8- CD161-)']
Length: 186, dtype: str

population_definition: <StringArray>
[                                  'WBC/CD19+SCC/CD19+,Freq. of,WBC',
                'WBC/CD19+SCC/CD19+/nQ1: CD27,, IgD+,Freq. of,CD19+',
               'WBC/CD19+SCC/CD19+/nQ2: CD27+,, IgD+,Freq. of,CD19+',
                'WBC/CD19+SCC/CD19+/nQ3: CD27+,, IgD,Freq. of,CD19+',
                 'WBC/CD19+SCC/CD19+/nQ4: CD27,, IgD,Freq. of,CD19+',
              'WBC/CD19+SCC/CD19+/nQ2: CD19+,, CD20+,Freq. of,CD19+',
               'WBC/CD19+SCC/CD19+/nQ3: CD19+,, CD20,Freq. of,CD19+',
              'WBC/CD19+SCC/CD19+/nQ2: CD19+,, CD27+,Freq. of,CD19+',
                  'WBC/CD19+SCC/CD19+/n transitional,Freq. of,CD19+',
 'WBC/CD19+SCC/CD19+/nQ2: CD19+,, CD27+/nPlasmablast,Freq. of,CD19+',
 ...
                                           'CD45+CD3+CD4+CD8-IL23r+',
                                            'CD45+CD3+CD4+CD8-TNFa+',
                                           'CD45+CD3+CD4+CD8-CD40L+',
                                            'CD45+CD3+CD4+CD8-CD69+',
                                             'CD45+CD3+CD4+CD8-IL2+',
                                             'CD45+CD3+CD4+CD8-IL4+',
                                            'CD45+CD3+CD8+CD4-CD69+',
                                            'CD45+CD3+CD8+CD4-IFNg+',
                                             'CD45+CD3+CD8+CD4-IL2+',
                                        'CD45+CD3+CD8+CD4-Perforin+']
Length: 999, dtype: str

name: <StringArray>
[                                  'Live cd45+ cells',
                                      'Naive b cells',
 'Memory class switched + non-class switched b cells',
                      'Memory class switched b cells',
                                            'B cells',
                                                  nan,
                             'Ab-secreting cells asc',
                                        'Neutrophils',
                                            'T cells',
                                        'Cd8 t cells',
                                        'Cd4 t cells',
                              'Tfh cxcr5+ cd4 t cell',
                             'Th1 cxcr3+ cd4 t cells',
                                            'Cd4 tcn',
                      'Naive cd4 + naive cd8 t cells',
                                            'Cd4 tem',
                                'Cd4 tem + cd4 temra',
                                            'Cd8 tcm',
                                            'Cd8 tem',
                                'Cd8 tem + cd8 temra',
                            'Cd56hi + cd56+ nk cells',
 'Classical + intermediate + non-classical monocytes',
                                   'Plasmacytoid dcs',
                                   'Conventional dcs',
                                'Classical monocytes',
                            'Neutrophils + basophils',
                                    'Conventional dc',
                   'Memory nonclass switched b cells',
                  'Conventional dc + plasmacytoid dc']
Length: 29, dtype: str

unit: <StringArray>
['cells/uL', 'cells', 'percentile', 'ul', 'percentage']
Length: 5, dtype: str

value: [176.22     112.7808    12.370644 ...  33.77      65.77      15.58    ]

material: <StringArray>
['blood', 'Other', 'peripheral blood mononuclear cell']
Length: 3, dtype: str

In [5]:
# Save the cleaned dataset to the cleaned_data folder
os.makedirs('../cleaned_data', exist_ok=True)
df.to_csv('../cleaned_data/flow_cleaned.csv', index=False)