In [9]:
#If running locally instead of colab
DATA_PATH = '../data/'

In [10]:
# Import required libraries
import os
import numpy as np
import pandas as pd

In [11]:
# Load the dataset
df = pd.read_csv(os.path.join(DATA_PATH,'challenge_hai.tsv'), sep='\t')
df = df.drop(columns=['hai_id', 'material'])
df['value'] = pd.to_numeric(df['value'], errors='coerce')
df = df[df['timepoint'].isin([0.0, 28.0, 365.0])]
df.head()

    participant_id  timepoint                          virus_strain  value
0  2024_UGA.ID_077          0              H1N1 A/California/7/2009     20
1  2024_UGA.ID_077          0                H1N1 A/Brisbane/2/2018      5
2  2024_UGA.ID_077          0  H1N1 A/Guangdong-Maonan/SWL1536/2019      5
3  2024_UGA.ID_077          0             H1N1 A/Victoria/2570/2019      5
4  2024_UGA.ID_077          0             H1N1 A/Victoria/4897/2022      5

In [12]:
df['hai_timepoint'] = 'HAI_' + df['virus_strain'].astype(str) + '_d' + df['timepoint'].astype(int).astype(str)

# Pivot the table
df_pivot = df.pivot_table(
    index='participant_id',
    columns='hai_timepoint',
    values='value'
)

# Reset index to make participant_id a regular column
df_pivot = df_pivot.reset_index()
df_pivot = df_pivot.rename_axis(None, axis=1)
for col in df_pivot.columns:
    if col != 'participant_id':
        df_pivot[col] = df_pivot[col].apply(lambda x: np.log2(x) if pd.notna(x) else x)

df_pivot

,participant_id,HAI_H1N1 A/Brisbane/2/2018_d0,HAI_H1N1 A/California/7/2009_d0,HAI_H1N1 A/Guangdong-Maonan/SWL1536/2019_d0,HAI_H1N1 A/Victoria/2570/2019_d0,HAI_H1N1 A/Victoria/4897/2022_d0,HAI_H3N2 A/Darwin/9/2021_d0,HAI_H3N2 A/Hong Kong/2671/2019_d0,HAI_H3N2 A/Hong Kong/4801/2014_d0,HAI_H3N2 A/Kansas/14/2017_d0,HAI_H3N2 A/Massachusetts/18/2022_d0,HAI_H3N2 A/Singapore/INFIMH-160019/2016_d0,HAI_H3N2 A/South Australia/34/2019_d0,HAI_H3N2 A/Tasmania/503/2020_d0,HAI_Vic B/Austria/1359417/2021_d0,HAI_Vic B/Colorado/6/2017_d0,HAI_Vic B/Washington/2/2019_d0,HAI_Yam B/Phuket/3073/2013_d0
0,2024_UGA.ID_077,2.321928,4.321928,2.321928,2.321928,2.321928,2.321928,4.321928,3.321928,3.321928,2.321928,3.321928,6.321928,3.321928,4.321928,2.321928,2.321928,4.321928
1,2024_UGA.ID_086,8.321928,9.321928,9.321928,6.321928,4.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,4.321928,3.321928,5.321928,5.321928,4.321928,5.321928
2,2024_UGA.ID_128,6.321928,7.321928,6.321928,6.321928,5.321928,6.321928,7.321928,7.321928,7.321928,7.321928,7.321928,8.321928,7.321928,3.321928,3.321928,3.321928,5.321928
3,2024_UGA.ID_170,3.321928,3.321928,3.321928,5.321928,2.321928,3.321928,5.321928,3.321928,4.321928,7.321928,4.321928,5.321928,6.321928,3.321928,2.321928,2.321928,3.321928
4,2024_UGA.ID_179,5.321928,3.321928,2.321928,6.321928,2.321928,4.321928,3.321928,2.321928,6.321928,3.321928,2.321928,4.321928,3.321928,5.321928,4.321928,4.321928,7.321928
5,2024_UGA.ID_215,2.321928,3.321928,2.321928,2.321928,2.321928,5.321928,7.321928,6.321928,6.321928,4.321928,6.321928,8.321928,8.321928,4.321928,5.321928,4.321928,3.321928
6,2024_UGA.ID_219,6.321928,6.321928,6.321928,5.321928,2.321928,3.321928,4.321928,2.321928,3.321928,4.321928,2.321928,4.321928,4.321928,5.321928,7.321928,7.321928,6.321928
7,2024_UGA.ID_275,3.321928,2.321928,5.321928,3.321928,3.321928,2.321928,3.321928,2.321928,3.321928,2.321928,2.321928,3.321928,4.321928,4.321928,4.321928,4.321928,7.321928
8,2024_UGA.ID_295,6.321928,2.321928,5.321928,6.321928,4.321928,2.321928,2.321928,2.321928,4.321928,3.321928,2.321928,4.321928,2.321928,9.321928,5.321928,4.321928,4.321928
9,2024_UGA.ID_296,5.321928,4.321928,4.321928,3.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,4.321928,2.321928,4.321928,3.321928,4.321928,3.321928
10,2024_UGA.ID_306,4.321928,5.321928,3.321928,5.321928,3.321928,2.321928,3.321928,3.321928,4.321928,2.321928,3.321928,5.321928,4.321928,6.321928,4.321928,3.321928,5.321928
11,2024_UGA.ID_313,5.321928,6.321928,4.321928,5.321928,3.321928,3.321928,4.321928,4.321928,5.321928,3.321928,4.321928,5.321928,5.321928,4.321928,4.321928,3.321928,4.321928
12,2024_UGA.ID_321,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,3.321928,2.321928,2.321928,2.321928,2.321928,3.321928
13,2024_UGA.ID_335,5.321928,5.321928,5.321928,5.321928,2.321928,3.321928,5.321928,5.321928,6.321928,4.321928,5.321928,7.321928,6.321928,4.321928,4.321928,3.321928,5.321928
14,2024_UGA.ID_340,2.321928,2.321928,3.321928,5.321928,5.321928,3.321928,5.321928,5.321928,5.321928,2.321928,5.321928,6.321928,6.321928,5.321928,7.321928,6.321928,6.321928
15,2024_UGA.ID_352,6.321928,6.321928,5.321928,5.321928,4.321928,3.321928,5.321928,4.321928,2.321928,4.321928,4.321928,5.321928,5.321928,5.321928,5.321928,5.321928,6.321928
16,2024_UGA.ID_353,5.321928,6.321928,2.321928,4.321928,2.321928,4.321928,6.321928,5.321928,4.321928,2.321928,4.321928,6.321928,5.321928,4.321928,4.321928,4.321928,2.321928
17,2024_UGA.ID_368,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,3.321928,2.321928,2.321928,4.321928
18,2024_UGA.ID_404,6.321928,5.321928,6.321928,2.321928,2.321928,2.321928,5.321928,4.321928,2.321928,2.321928,4.321928,3.321928,5.321928,5.321928,7.321928,6.321928,7.321928
19,2024_UGA.ID_411,6.321928,6.321928,4.321928,6.321928,3.321928,2.321928,4.321928,3.321928,4.321928,3.321928,2.321928,4.321928,3.321928,3.321928,4.321928,4.321928,5.321928
20,2024_UGA.ID_412,5.321928,5.321928,3.321928,5.321928,4.321928,2.321928,6.321928,5.321928,2.321928,2.321928,5.321928,5.321928,7.321928,4.321928,5.321928,5.321928,5.321928
21,2024_UGA.ID_430,5.321928,5.321928,5.321928,4.321928,4.321928,2.321928,3.321928,5.321928,6.321928,2.321928,5.321928,6.321928,6.321928,4.321928,4.321928,3.321928,4.321928
22,2024_UGA.ID_432,4.321928,5.321928,3.321928,4.321928,2.321928,2.321928,3.321928,2.321928,4.321928,3.321928,2.321928,5.321928,3.321928,4.321928,5.321928,4.321928,3.321928
23,2024_UGA.ID_438,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,3.321928,2.321928,2.321928,2.321928,4.321928
24,2024_UGA.ID_443,4.321928,4.321928,3.321928,3.321928,3.321928,6.321928,6.321928,6.321928,6.321928,6.321928,6.321928,7.321928,7.321928,3.321928,5.321928,4.321928,7.321928
25,2024_UGA.ID_448,4.321928,4.321928,3.321928,3.321928,2.321928,7.321928,8.321928,7.321928,5.321928,6.321928,7.321928,8.321928,8.321928,4.321928,5.321928,5.321928,7.321928
26,2024_UGA.ID_455,6.321928,5.321928,4.321928,4.321928,4.321928,7.321928,8.321928,7.321928,8.321928,9.321928,7.321928,9.321928,8.321928,6.321928,5.321928,5.321928,6.321928
27,2024_UGA.ID_461,7.321928,6.321928,7.321928,6.321928,6.321928,2.321928,4.321928,3.321928,4.321928,2.321928,3.321928,5.321928,4.321928,4.321928,5.321928,5.321928,3.321928
28,2024_UGA.ID_507,5.321928,6.321928,4.321928,4.321928,3.321928,3.321928,5.321928,4.321928,4.321928,4.321928,4.321928,6.321928,6.321928,3.321928,4.321928,4.321928,7.321928
29,2024_UGA.ID_512,6.321928,7.321928,5.321928,5.321928,5.321928,2.321928,5.321928,4.321928,4.321928,2.321928,4.321928,6.321928,5.321928,3.321928,4.321928,3.321928,5.321928
30,2024_UGA.ID_572,6.321928,6.321928,4.321928,5.321928,4.321928,2.321928,2.321928,2.321928,3.321928,2.321928,2.321928,2.321928,3.321928,7.321928,4.321928,4.321928,5.321928
31,2024_UGA.ID_586,4.321928,6.321928,2.321928,4.321928,2.321928,5.321928,10.321928,7.321928,6.321928,4.321928,7.321928,11.321928,8.321928,5.321928,5.321928,5.321928,7.321928
32,2024_UGA.ID_589,3.321928,2.321928,2.321928,2.321928,2.321928,2.321928,4.321928,2.321928,3.321928,2.321928,2.321928,4.321928,3.321928,2.321928,2.321928,2.321928,5.321928
33,2024_UGA.ID_594,5.321928,6.321928,4.321928,5.321928,4.321928,2.321928,3.321928,4.321928,4.321928,3.321928,4.321928,4.321928,3.321928,4.321928,3.321928,3.321928,4.321928
34,2024_UGA.ID_600,2.321928,2.321928,2.321928,2.321928,2.321928,2.321928,4.321928,2.321928,2.321928,2.321928,2.321928,6.321928,2.321928,4.321928,3.321928,4.321928,5.321928
35,2024_UGA.ID_614,2.321928,2.321928,2.321928,5.321928,2.321928,2.321928,4.321928,5.321928,3.321928,2.321928,5.321928,4.321928,3.321928,2.321928,4.321928,3.321928,2.321928
36,2024_UGA.ID_629,3.321928,4.321928,2.321928,6.321928,2.321928,4.321928,5.321928,6.321928,5.321928,3.321928,6.321928,7.321928,8.321928,4.321928,2.321928,2.321928,4.321928
37,2024_UGA.ID_632,6.321928,6.321928,5.321928,5.321928,4.321928,2.321928,3.321928,3.321928,4.321928,2.321928,3.321928,5.321928,4.321928,4.321928,4.321928,3.321928,5.321928
38,2024_UGA.ID_649,4.321928,5.321928,2.321928,4.321928,2.321928,3.321928,5.321928,4.321928,4.321928,4.321928,4.321928,7.321928,6.321928,7.321928,6.321928,5.321928,6.321928
39,2024_UGA.ID_683,8.321928,8.321928,7.321928,7.321928,5.321928,2.321928,7.321928,8.321928,4.321928,2.321928,8.321928,10.321928,7.321928,3.321928,4.321928,3.321928,6.321928

In [13]:
# Print all columns and their unique values
for col in df_pivot.columns:
    print(f"{col}: {df_pivot[col].unique()}\n")

participant_id: ['2024_UGA.ID_077' '2024_UGA.ID_086' '2024_UGA.ID_128' '2024_UGA.ID_170'
 '2024_UGA.ID_179' '2024_UGA.ID_215' '2024_UGA.ID_219' '2024_UGA.ID_275'
 '2024_UGA.ID_295' '2024_UGA.ID_296' '2024_UGA.ID_306' '2024_UGA.ID_313'
 '2024_UGA.ID_321' '2024_UGA.ID_335' '2024_UGA.ID_340' '2024_UGA.ID_352'
 '2024_UGA.ID_353' '2024_UGA.ID_368' '2024_UGA.ID_404' '2024_UGA.ID_411'
 '2024_UGA.ID_412' '2024_UGA.ID_430' '2024_UGA.ID_432' '2024_UGA.ID_438'
 '2024_UGA.ID_443' '2024_UGA.ID_448' '2024_UGA.ID_455' '2024_UGA.ID_461'
 '2024_UGA.ID_507' '2024_UGA.ID_512' '2024_UGA.ID_572' '2024_UGA.ID_586'
 '2024_UGA.ID_589' '2024_UGA.ID_594' '2024_UGA.ID_600' '2024_UGA.ID_614'
 '2024_UGA.ID_629' '2024_UGA.ID_632' '2024_UGA.ID_649' '2024_UGA.ID_683']

HAI_H1N1 A/Brisbane/2/2018_d0: [2.32192809 8.32192809 6.32192809 3.32192809 5.32192809 4.32192809
 7.32192809]

HAI_H1N1 A/California/7/2009_d0: [4.32192809 9.32192809 7.32192809 3.32192809 6.32192809 2.32192809
 5.32192809 8.32192809]

HAI_H1N1 A/Guangdong-Maonan/SWL1536/2019_d0: [2.32192809 9.32192809 6.32192809 3.32192809 5.32192809 4.32192809
 7.32192809]

HAI_H1N1 A/Victoria/2570/2019_d0: [2.32192809 6.32192809 5.32192809 3.32192809 4.32192809 7.32192809]

HAI_H1N1 A/Victoria/4897/2022_d0: [2.32192809 4.32192809 5.32192809 3.32192809 6.32192809]

HAI_H3N2 A/Darwin/9/2021_d0: [2.32192809 6.32192809 3.32192809 4.32192809 5.32192809 7.32192809]

HAI_H3N2 A/Hong Kong/2671/2019_d0: [ 4.32192809  2.32192809  7.32192809  5.32192809  3.32192809  6.32192809
  8.32192809 10.32192809]

HAI_H3N2 A/Hong Kong/4801/2014_d0: [3.32192809 2.32192809 7.32192809 6.32192809 4.32192809 5.32192809
 8.32192809]

HAI_H3N2 A/Kansas/14/2017_d0: [3.32192809 2.32192809 7.32192809 4.32192809 6.32192809 5.32192809
 8.32192809]

HAI_H3N2 A/Massachusetts/18/2022_d0: [2.32192809 7.32192809 3.32192809 4.32192809 6.32192809 9.32192809]

HAI_H3N2 A/Singapore/INFIMH-160019/2016_d0: [3.32192809 2.32192809 7.32192809 4.32192809 6.32192809 5.32192809
 8.32192809]

HAI_H3N2 A/South Australia/34/2019_d0: [ 6.32192809  4.32192809  8.32192809  5.32192809  3.32192809  7.32192809
  2.32192809  9.32192809 11.32192809 10.32192809]

HAI_H3N2 A/Tasmania/503/2020_d0: [3.32192809 7.32192809 6.32192809 8.32192809 4.32192809 2.32192809
 5.32192809]

HAI_Vic B/Austria/1359417/2021_d0: [4.32192809 5.32192809 3.32192809 9.32192809 6.32192809 2.32192809
 7.32192809]

HAI_Vic B/Colorado/6/2017_d0: [2.32192809 5.32192809 3.32192809 4.32192809 7.32192809 6.32192809]

HAI_Vic B/Washington/2/2019_d0: [2.32192809 4.32192809 3.32192809 7.32192809 6.32192809 5.32192809]

HAI_Yam B/Phuket/3073/2013_d0: [4.32192809 5.32192809 3.32192809 7.32192809 6.32192809 2.32192809]

In [14]:
# Save the cleaned dataset to the cleaned_data folder
os.makedirs('../cleaned_data', exist_ok=True)
df_pivot.to_csv(os.path.join("..", 'cleaned_data', 'challenge_hai_cleaned.csv'), index=False)